name: Distribute Test Version to Firebase

on:
  push:
    branches: [ develop ]

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decode google-services.json
        env:
          FIREBASE_SETTINGS: ${{ secrets.FIREBASE_SETTINGS }}
        run: echo FIREBASE_SETTINGS > $GITHUB_WORKSPACE/app/src/google-services.json
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
      - name: install firebase tool
        run: |
          yarn global add firebase-tools
      - name: setup fastlane
        run:  gem install bundler && bundle install
      - name: Upload to Firebase
        run: bundle exec fastlane android dev_firebase
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
